### ISSUE TITLE
key/value formatting is not supported

### ISSUE THREAD

**Issue by jney** [komuw/meli#105]
Key/value formatting for `environment` looks to be not supported

```
environment:
      KEY: value
```

giving me such error:

```
$ meli -up
2018/06/08 14:30:51 yaml: unmarshal errors:
  line 9: cannot unmarshal !!map into []string
```

but formatting:

```
environment:
      - KEY=value
```

looks to work

**Comment by komuw** [comment]
yeah, `:` is currently not supported yet. 
but it seems like something trivial to do. something akin to; https://github.com/komuw/meli/blob/efa39305a9e65da8fa255a4e3df9e67c6b74e349/format.go#L27-L36

do you require the `:` format or can you live with `=` format?

**Comment by jney** [comment]
sure, i just wanted to mention, let's live with it
